name: CleanupDB

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  ping-cleanupdb:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Call /cleanupDB endpoint
        run: |
          echo "Calling /cleanupDB endpoint..."
          RESPONSE=$(curl -s "${{ secrets.CLEANUP_URL }}")
          echo "Raw Response: $RESPONSE"
          MESSAGE=$(echo $RESPONSE | jq -r '.message')
          DELETED_ROOMS=$(echo $RESPONSE | jq -c '.deletedRooms')
          echo "$MESSAGE"
          echo "Deleted Rooms: $DELETED_ROOMS"
